added burgers program to exercises package
marekk1992/JavaMasterclass_Section7 pull request #3
Opened 2022-02-08 19:30 UTC by marekk1992

2022-02-08 19:43 UTC, RobertasVainickas requested changes

2022-02-08 19:43 UTC, RobertasVainickas commented on src/exercises/burgers/Hamburger.java
> +
As per requirements: The basic hamburger should have the following items: Bread roll type, meat **and up to 4 additional additions**
I think you miss additions here.
The same applies to subclasses of Hamburger

2022-02-08 20:28 UTC, RobertasVainickas requested changes

2022-02-08 20:28 UTC, RobertasVainickas commented on src/exercises/burgers/Hamburger.java
> +    private String additive1 = "Cucumber";
It should not be your hardcoded values.
What if I would like to add mustard as an additive to hamburger? You would need to create one more variable in such case which is not right.

2022-02-08 20:28 UTC, RobertasVainickas commented on src/exercises/burgers/HealthyBurger.java
> +    public String addAdditives(int additive) {
I think the approach with 4 different methods for each of the additives was much better

2022-02-09 16:20 UTC, marekk1992 commented on src/exercises/burgers/HealthyBurger.java
> +    public String addAdditives(int additive) {
Fixed somehow

2022-02-09 16:52 UTC, RobertasVainickas requested changes

2022-02-09 16:52 UTC, RobertasVainickas commented on src/exercises/burgers/Hamburger.java
> +    private String additive1;
I don't really like numbers in variable names, it is optional but I would suggest using something like `firstAdditive`
The  same goes for the method naming. Later on when you create  a hamburger object  and add additives, the code starts looking more like natural language:  
`hamburger.addFirstAdditive(....);`
instead of 
`hamburger.addAdditive1(....);`

2022-02-09 16:52 UTC, RobertasVainickas commented on src/exercises/burgers/Hamburger.java
> +    private double priceOfAdditives;
This is optional, but seems that this field does not bring any value. 
What I mean is, you already have prices of all 4  additives when object is constructed, so you can just  have  a method getPriceOfAllAditives() which calculates total sum  (which is also not sure if necessary) or you can calculate it directly in the method  that  calculates total burger's price. 
It is up to you, you can leave it as is, I just wanted you to consider this case.

2022-02-09 16:52 UTC, RobertasVainickas commented on src/exercises/burgers/HealthyBurger.java
> +    private String additive4;
additives 1 to 4 are not necessary here, because they are in parent class, which this burger inherits

2022-02-09 16:52 UTC, RobertasVainickas commented on src/exercises/burgers/DeluxeBurger.java
> +    private String chips;
I think you should stick to the naming of additives in this class too. What if requirement would  change and you would need  to have fries instead of chips? You would need to rename the variable, which is not right, because only  the value of the variable matters.

2022-02-09 16:52 UTC, RobertasVainickas commented on src/exercises/burgers/DeluxeBurger.java
> +    public DeluxeBurger(String name, String breadRollType, String meat, double basePrice, String chips, String drink) {
Requirements say that you should find a way to automatically add chips and drink when object is created.
Currently, the user of the class can decide how to construct it, and instead of chips and drink, he can pass whatever he wants

2022-02-09 16:52 UTC, RobertasVainickas commented on src/exercises/burgers/Hamburger.java
> +        System.out.println(getAdditive1() + " is added to burger composition, total cost now is " + getFinalPrice());
You don't have to call getter to get additive from inside the class here. This field is accessible from the class, so use it dirrectly. This applies to all other places in this PR.

2022-02-09 18:53 UTC, marekk1992 commented on src/exercises/burgers/Hamburger.java
> +    private String additive1;
Fixed

2022-02-09 18:53 UTC, marekk1992 commented on src/exercises/burgers/Hamburger.java
> +    private double priceOfAdditives;
Fixed by creating method for calculation of sum of all additives.

2022-02-09 18:54 UTC, marekk1992 commented on src/exercises/burgers/HealthyBurger.java
> +    private String additive4;
Removed

2022-02-09 18:54 UTC, marekk1992 commented on src/exercises/burgers/DeluxeBurger.java
> +    private String chips;
Changed

2022-02-09 18:55 UTC, marekk1992 commented on src/exercises/burgers/DeluxeBurger.java
> +    public DeluxeBurger(String name, String breadRollType, String meat, double basePrice, String chips, String drink) {
Chips and drink added as default value in constructor

2022-02-09 18:56 UTC, marekk1992 commented on src/exercises/burgers/Hamburger.java
> +        System.out.println(getAdditive1() + " is added to burger composition, total cost now is " + getFinalPrice());
Fixed in all classes

2022-02-09 18:57 UTC, RobertasVainickas requested changes

2022-02-09 18:57 UTC, RobertasVainickas commented on src/exercises/burgers/HealthyBurger.java
> +        return super.getPriceOfAllAdditives();
It will return  price of first 4 additives, but this type of burger contains 6 in total.

2022-02-09 19:36 UTC, marekk1992 commented on src/exercises/burgers/HealthyBurger.java
> +        return super.getPriceOfAllAdditives();
Fixed

2022-02-09 19:37 UTC, RobertasVainickas approved these changes

2022-02-10 07:03 UTC, RobertasVainickas requested changes

2022-02-10 08:20 UTC, RobertasVainickas requested changes

2022-02-10 08:20 UTC, RobertasVainickas commented on src/exercises/burgers/DeluxeBurger.java
> +        super.addFirstAdditive(additive);
DeluxeBurger should not allow adding additives

2022-02-10 10:38 UTC, marekk1992 commented on src/exercises/burgers/DeluxeBurger.java
> +        super.addFirstAdditive(additive);
Fixed

2022-02-10 10:40 UTC, RobertasVainickas approved these changes

2022-02-15 05:15 UTC, merged